from flask import Blueprint, render_template, request, send_file, flash, redirect, url_for
from flask_login import login_required, current_user
from database.models import BGRequest, AuditLog, User, db
from utils.decorators import hod_required
from utils.helpers import log_action, format_currency
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
import io
from datetime import datetime, date

reports = Blueprint('reports', __name__)

@reports.route('/reports')
@login_required
def reports_page():
    return render_template('reports.html')

@reports.route('/reports/bg-export')
@login_required
def bg_export():
    # Filters
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')
    dept_filter = request.args.get('department')
    status_filter = request.args.get('status')
    
    query = BGRequest.query
    if current_user.role == 'Employee':
        query = query.filter_by(user_id=current_user.id)
    if start_date:
        query = query.filter(BGRequest.date_of_request >= datetime.strptime(start_date, '%Y-%m-%d').date())
    if end_date:
        query = query.filter(BGRequest.date_of_request <= datetime.strptime(end_date, '%Y-%m-%d').date())
    if status_filter:
        query = query.filter_by(status=status_filter)
    
    bg_requests = query.order_by(BGRequest.date_of_request.desc()).all()
    
    # Create Excel
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "BG Report"
    
    # Header styling
    header_fill = PatternFill(start_color="1E3A5F", end_color="1E3A5F", fill_type="solid")
    header_font = Font(name='Calibri', bold=True, color="FFFFFF", size=11)
    alt_fill = PatternFill(start_color="EBF2FF", end_color="EBF2FF", fill_type="solid")
    thin_border = Border(
        left=Side(style='thin'), right=Side(style='thin'),
        top=Side(style='thin'), bottom=Side(style='thin')
    )
    
    # Title row
    ws.merge_cells('A1:R1')
    ws['A1'] = 'BANK GUARANTEE MANAGEMENT SYSTEM - BG REPORT'
    ws['A1'].font = Font(name='Calibri', bold=True, size=14, color="1E3A5F")
    ws['A1'].alignment = Alignment(horizontal='center')
    
    ws.merge_cells('A2:R2')
    ws['A2'] = f'Generated on: {datetime.now().strftime("%d-%m-%Y %H:%M")} | Generated by: {current_user.name}'
    ws['A2'].alignment = Alignment(horizontal='center')
    ws.row_dimensions[2].height = 20
    
    # Headers
    headers = ['#', 'P.No', 'Employee Name', 'Department', 'Location', 'Date of Request',
               'Work Order No', 'Type of Work', 'Job Value (₹)', 'Party Name',
               'Nature of BG', 'BG Amount (₹)', 'BG Expiry Date', 'Claim Period (Days)',
               'Approval Type', 'Status', 'First Owner', 'Remarks']
    
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=4, column=col, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        cell.border = thin_border
    
    ws.row_dimensions[4].height = 30
    ws.freeze_panes = 'A5'
    
    # Data rows
    for idx, req in enumerate(bg_requests, 1):
        row = idx + 4
        data = [
            idx, req.p_no, req.employee_name,
            req.department.name if req.department else '-',
            req.location,
            req.date_of_request.strftime('%d-%m-%Y') if req.date_of_request else '-',
            req.work_order_no, req.type_of_work,
            req.job_value, req.party_name, req.nature_of_bg,
            req.bg_amount,
            req.bg_expiry_date.strftime('%d-%m-%Y') if req.bg_expiry_date else '-',
            req.bg_claim_period, req.approval_type, req.status,
            req.first_owner_name, req.remarks or '-'
        ]
        
        fill = alt_fill if idx % 2 == 0 else PatternFill(fill_type=None)
        for col, value in enumerate(data, 1):
            cell = ws.cell(row=row, column=col, value=value)
            cell.border = thin_border
            cell.fill = fill
            cell.alignment = Alignment(horizontal='center', vertical='center')
        
        # Color status
        status_cell = ws.cell(row=row, column=16)
        colors = {'Approved': '27AE60', 'Rejected': 'E74C3C', 'Pending': 'F39C12'}
        if req.status in colors:
            status_cell.fill = PatternFill(start_color=colors[req.status], end_color=colors[req.status], fill_type="solid")
            status_cell.font = Font(color="FFFFFF", bold=True)
    
    # Column widths
    col_widths = [5, 12, 20, 18, 15, 16, 18, 20, 15, 20, 15, 15, 16, 15, 14, 12, 18, 25]
    for i, width in enumerate(col_widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = width
    
    # Save to buffer
    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    
    log_action('BG Report exported to Excel', 'bg_requests')
    filename = f"BG_Report_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx"
    return send_file(output, mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                     as_attachment=True, download_name=filename)

@reports.route('/reports/audit-log')
@login_required
def audit_export():
    logs = AuditLog.query.order_by(AuditLog.timestamp.desc()).limit(500).all()
    
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Audit Log"
    
    header_fill = PatternFill(start_color="1E3A5F", end_color="1E3A5F", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF")
    
    ws.merge_cells('A1:G1')
    ws['A1'] = 'AUDIT TRAIL REPORT'
    ws['A1'].font = Font(bold=True, size=14, color="1E3A5F")
    ws['A1'].alignment = Alignment(horizontal='center')
    
    headers = ['#', 'User', 'Action', 'Table', 'Record ID', 'IP Address', 'Timestamp']
    for col, h in enumerate(headers, 1):
        cell = ws.cell(row=3, column=col, value=h)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center')
    
    ws.freeze_panes = 'A4'
    for idx, log in enumerate(logs, 1):
        user = User.query.get(log.user_id) if log.user_id else None
        ws.append([idx, user.name if user else 'System', log.action,
                   log.table_name or '-', log.record_id or '-',
                   log.ip_address or '-',
                   log.timestamp.strftime('%d-%m-%Y %H:%M:%S') if log.timestamp else '-'])
    
    for col in ['A', 'B', 'C', 'D', 'E', 'F', 'G']:
        ws.column_dimensions[col].width = 20
    
    output = io.BytesIO()
    wb.save(output)
    output.seek(0)
    
    filename = f"Audit_Log_{datetime.now().strftime('%Y%m%d_%H%M')}.xlsx"
    return send_file(output, mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                     as_attachment=True, download_name=filename)
